atg_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from ckeditor_uploader import views
# from . import blog
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('ckeditor/',include('ckeditor_uploader.urls')),
     path('ckeditor/upload/', login_required(views.upload), name='ckeditor_upload'),
    path('ckeditor/browse/', (login_required(views.browse)), name='ckeditor_browse'),
    path('accounts/', include('allauth.urls')),
    path("",include('blog.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
app_name = 'blog'

urlpatterns = [

    path("",views.home,name='home'),
    path("my_posts/", views.post_list_view, name='post-list'),
    path("add/post/", views.post_form, name = "add-post"),
    # path('signup/', views.signup, name = "signup"),
    path('search/',views.post_search_view, name='search-user'),
    path('delete_post/<int:pk>/',views.delete_post_view, name="delete-post"),
    path('edit_post/<int:pk>/',views.edit_post_view,name='edit-post'),

]

blog/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from django.conf import settings
from simplemathcaptcha.fields import MathCaptchaField
POST_CHOICE = (
    ('PUB','Public'),
    ('PVT','Private'),
)

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    post_title = models.CharField(max_length = 200,unique = True)
    post_description = RichTextUploadingField()
    is_published = models.BooleanField(default = False)
    published_date = models.DateTimeField(auto_now_add = True)
    post_type = models.CharField(choices = POST_CHOICE, max_length = 3)
    # follows = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name = 'follows')

    class Meta:
        db_table = 'post'

    def __str__(self):
        return self.post_title
    #
    # def get_delete_post_url(self):
    #     return reverse('blog:post-delete', kwargs={
    #                 'pk':self.pk
    #     })


    def publish_post(self):
        self.is_published = True
        return self.is_published

class UserProfile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    class Meta:
        db_table = 'user'

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from .models import Post
import random
from django.conf import settings

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields  = ['post_title','post_description','is_published','post_type']
# from allauth.account.forms import SignupForm
# from simplemathcaptcha.fields import MathCaptchaField
# from simplemathcaptcha.widgets import MathCaptchaWidget
#
# class MyCustomSignupForm(SignupForm):
#     def __init__(self, *args, **kwargs):
#         super(MyCustomSignupForm, self).__init__(*args, **kwargs)
#
#         self.fields['captcha'] = MathCaptchaField(widget=MathCaptchaWidget(question_tmpl=('What is %(num1)i %(operator)s %(num2)i ? ')),
#     error_messages = {'invalid': ('Please check your math and try again.'), 'invalid_number': ('Enter a whole number.')})
#     def save(self, request):
#         captcha = self.cleaned_data.get('captcha')
#
#         user = super(MyCustomSignupForm, self).save(request)
# 
# class UserSearchForm(forms.ModelForm):
#     class Meta:
#         model = settings.AUTH_USER_MODEL
#         fields = 'user_username'

blog/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.views.generic import TemplateView
from django.shortcuts import redirect
# Create your views here.
from .forms import PostForm
from .models import Post
from django.conf import   settings
from django.db.models import Q
# from django.contrib.auth.models import User



@login_required
def post_list_view(request):
    post_list = Post.objects.filter(user = request.user, is_published = True).order_by('-published_date')
    context = {'post_list':post_list}
    return render(request,'post_list.html',context)

@login_required
def home(request):
    post_list = Post.objects.filter(is_published=True,post_type="PUB").order_by('-published_date')
    context = {'post_list':post_list}
    return render(request,'home.html',context)
    
@login_required
def post_form(request):
    user = request.user
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            # user = user
            post_title = form.cleaned_data.get('post_title')
            post_description = form.cleaned_data.get('post_description')
            is_published = form.cleaned_data.get('is_published')
            type_of_post = form.cleaned_data.get('type_of_post')
            post = form.save(commit = False)
            post.user = user
            post.save()
            return redirect("/")
    else:
        form = PostForm()
        context = {'form':form}
        return render(request,'post_form.html',context)


@login_required
def post_search_view(request):
    query = request.GET.get('q').lower()
    object_list = Post.objects.filter(Q(post_title__contains=query) | Q(post_description__contains=query) | Q(user__username__contains=query),is_published = True, post_type ="PUB")
    context = {'object_list':object_list}
    return render(request,'search_result.html',context)

@login_required
def delete_post_view(request,pk):
    post = Post.objects.get(pk=pk)
    post.delete()
    return redirect("/")

@login_required
def edit_post_view(request,pk):
    post = Post.objects.get(pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST,instance=post)
        if form.is_valid():
            form.save()
            post.save()
            return redirect("/")
        else:
            form = PostForm(instance = post)
    else:
        form = PostForm(instance = post)
    return render(request,'edit_post.html',context={'form':form})

blog/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>

    <!-- BOOTSTRAP 4 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="/">MY BLOG</a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
    {% if user.is_authenticated %}
    <li class="nav-item active">
      <a class="nav-link" href="/add/post/">Add Post</a>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="/accounts/logout/">Logout</a>
    </li>
    <li class="nav-item disabled nav-link">
    <strong style="color:white">Hey, {{user.username}}</strong>
    </li>&nbsp;&nbsp;
    <li class="nav-item active">
      <a class="nav-link" href="/my_posts/">My Posts</a>
    </li>

    <form   action="/search/" method="get" class="form-inline my-2 my-lg-0">
      <input style="width:400px" class="form-control mr-sm-2" type="text" placeholder="Search posts with username or title or description..." aria-label="Search" name="q">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    {% else %}
      <li class="nav-item">
        <a class="nav-link" href="/accounts/signup/">Register</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/accounts/login/">Login</a>
      </li>
      {% endif %}
    </ul>

  </div>
</nav>

  <div class="container">
    <div class="container">

      {% block content %}

      {% endblock %}

    </div>

  </div>


  </body>
</html>

blog/templates/edit_post.html
{% extends 'base.html' %}

{% block content %}

<form class="form-group"  method="post">
    {% csrf_token %}
    {{form.media}}
    {{form.as_p|safe}}
  <input type="submit" class="btn btn-success" name="" value="Submit">
</form>

{% endblock %}

blog/templates/home.html
{% extends 'base.html' %}

{% block content %}
<br><br>
{% for post in post_list %}

<h1 style="font-size:60px;font-style:italic"><b>{{post.post_title}}</b></h1>
<h5><b><i>By : {{post.user.username}}</i></b></h5>
<p>{{post.post_description|safe}}</p>
<i><b>Posted on : {{post.published_date}}</b></i>
<br><hr style="color:black;border:1px solid black"><br>
{% endfor %}




{% endblock %}

blog/templates/post_form.html
{% extends 'base.html' %}

{% block content %}

<form class=""  method="post">
  {% csrf_token %}
    <h1>Create Post!!!</h1>
    {{form.media}}
    {{form.as_p|safe}}
    <button class="btn btn-primary" type="submit" name="button">Submit</button>
</form>










{% endblock %}

blog/templates/post_list.html
{% extends 'base.html' %}
{% block content %}

  <br>
  {% for post in post_list %}
    <i>  <h1 style ="font-size : 70px;">{{post.post_title}}</h1></i>
    <strong style = "font-weight : 600"><i>By : {{user.username}}</i></strong>
    <p>{{post.post_description|safe}}</p>
    <strong style = "font-weight : 600"><i>Published at : {{post.published_date}}</i></strong>
    <br>
    <a class="btn btn-info " href="{% url 'blog:edit-post' pk=post.pk %}">Edit</a>&nbsp;&nbsp;&nbsp;
    <a class="btn btn-danger" href="{% url 'blog:delete-post'  pk=post.pk %}">Delete</a>
    <br><hr style="color:black; border:1px solid black"><br>

  {% endfor %}


{% endblock %}

blog/templates/search_result.html
{% extends 'base.html' %}

{% block content %}

{% for i in object_list %}
      <h2 style="font-size:50px;"><b><i>{{i.post_title}}</i></b></h2>
    <p>{{i.post_description|safe}}</p>
    <h5><i><b>By : {{i.user.username}}</b></i></h5>
    <br><hr><br>
{% endfor %}


{% endblock %}

blog/templates/signup.html
{% extends 'base.html' %}

{% block content %}

<form class="" action="" method="post">
  {% csrf_token %}
  {{form.media}}
  {{form.as_p}}
  <button type="submit" name="button">Sign Up</button>
</form>


{% endblock %}